version: '3'

services:
  app:
    build: ./images/app
    volumes:
      - ./images/app/volume:/app
      - ./conf.d/:/conf.d/:ro
    ports:
      - 8080:8080
    environment:
      KEY_PASSPHRASE: qweqweasd
